[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "group14_experiments"
version = "0.0.1"
description = "AT1-Kaggle Competition"
authors = [
  { name = "group14" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
dependencies = [
    "jupyterlab==4.6.1",
    "loguru",
    "mkdocs",
    "pandas==2.2.2",
    "pip",
    "python-dotenv",
    "ruff",
    "scikit-learn==1.6.1",
    "tqdm",
    "typer",
]
requires-python = "~=3.12.0"


[tool.ruff]
line-length = 99
src = ["group14_experiments"]
include = ["pyproject.toml", "group14_experiments/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["group14_experiments"]
force-sort-within-sections = true

